# Generated by Django 5.0.4 on 2024-08-26 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_userprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilestudent',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userprofileteacher',
            name='name',
        ),
        migrations.AlterField(
            model_name='userprofilestudent',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userprofilestudent',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofilestudent',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofilestudent',
            name='standard',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofilestudent',
            name='stream',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofilestudent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofileteacher',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userprofileteacher',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofileteacher',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='userprofileteacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
