# Generated by Django 5.0.4 on 2024-08-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_userprofilestudent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileteacher',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofilestudent',
            name='gender',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofilestudent',
            name='phone_number',
            field=models.CharField(default=' ', max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofilestudent',
            name='standard',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofilestudent',
            name='stream',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofileteacher',
            name='bio',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='userprofileteacher',
            name='phone_number',
            field=models.CharField(default=' ', max_length=15),
        ),
    ]
