# Generated by Django 5.0.4 on 2024-08-26 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userprofileteacher_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileteacher',
            name='name',
        ),
    ]
