# Generated by Django 5.0.4 on 2024-08-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_userprofileteacher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilestudent',
            name='profile_pic',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileteacher',
            name='profile_pic',
            field=models.URLField(blank=True, null=True),
        ),
    ]
