# Generated by Django 5.1 on 2024-08-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_userprofilestudent_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
