# Generated by Django 5.1 on 2024-08-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_comment_parent_id_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilestudent',
            name='gender',
            field=models.CharField(blank=True, default=' ', max_length=225, null=True),
        ),
    ]
