# Generated by Django 5.1 on 2024-09-02 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_standard_stream_remove_standard_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='asset_sel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.libasset'),
        ),
    ]
