# Generated by Django 5.1 on 2024-09-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_lecture_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='lecture_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='thumbnail_url',
            field=models.URLField(default=1111),
            preserve_default=False,
        ),
    ]
