# Generated by Django 5.1 on 2024-09-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_userprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='progress_percentage',
        ),
        migrations.AddField(
            model_name='userprogress',
            name='last_watched_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
