# Generated by Django 5.1 on 2024-09-03 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_userprogress_progress_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='last_watched_timestamp',
        ),
    ]
