# Generated by Django 5.1 on 2024-09-08 08:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_userprogress_last_watched_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='libasset',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
