# Generated by Django 5.1 on 2024-09-08 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_lecture_is_verified_alter_libasset_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libasset',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.standard'),
        ),
        migrations.AlterField(
            model_name='libasset',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.stream'),
        ),
    ]
