# Generated by Django 5.1 on 2024-09-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_libasset_standard_alter_libasset_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libasset',
            name='standard',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='libasset',
            name='stream',
            field=models.TextField(blank=True, null=True),
        ),
    ]
