# Generated by Django 5.1 on 2024-09-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_libasset_standard_alter_libasset_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='libasset',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
