# Generated by Django 5.1 on 2024-09-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_libasset_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
