# Generated by Django 5.1 on 2024-09-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_lecture_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libasset',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
